[package]
name = "marketprotobuf-lib"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
protox = "0.9.0"
prost-build = "0.14.1"

[dependencies]
prost = "0.14.1"
bytes = "1.10.1"
